### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by AndriesVansweevelt**
I added the files necessary for a Dutch version of the Cinderella applets.

### CODE REVIEW

**Comment by porst17** [comment]
Thanks a lot for providing the dutch translation. I checked your work and it looks promising. Only the page titles of the individual applets are missing. They are in the separate file `js/functions.js`. Please add

```
   if(name=="A1_nl") return "<b>Reflections:</b> Reflection of reflections";     
   if(name=="A2_nl") return "<b>Reflections:</b> Physical refelctions";    
   if(name=="A3_nl") return "<b>Reflections:</b> Kaleidoscopes";     
   if(name=="A4_nl") return "<b>Reflections:</b> Wallpapers";     

   if(name=="B1_nl") return "<b>Similarities:</b> Rotational symmetry";     
   if(name=="B2_nl") return "<b>Similarities:</b> Juxtapositions of four-gons";     
   if(name=="B3_nl") return "<b>Similarities:</b> Iterated similarities";     
   if(name=="B4_nl") return "<b>Similarities:</b> Iterating two similarities";     

   if(name=="C1_nl") return "<b>Solids:</b> Platonic solids";     
   if(name=="C2_nl") return "<b>Solids:</b> Archimedian solids";     
   if(name=="C3_nl") return "<b>Solids:</b> Nesting platonic solids";     
   if(name=="C4_nl") return "<b>Solids:</b> Morphing solids";     

   if(name=="D1_nl") return "<b>Packings:</b> Space filling polyhedra";     
   if(name=="D2_nl") return "<b>Packings:</b> Sierpinski tetrahedron";     
   if(name=="D3_nl") return "<b>Packings:</b> Sphere packings";     
   if(name=="D4_nl") return "<b>Packings:</b> Crystals and lattices";     

   if(name=="E1_nl") return "<b>Chaos:</b> Mirror chaos";     
   if(name=="E2_nl") return "<b>Chaos:</b> Conway's game of life";     
   if(name=="E3_nl") return "<b>Chaos:</b> Double pendulum";     
   if(name=="E4_nl") return "<b>Chaos:</b> Planet in a force field";     

   if(name=="F1_nl") return "<b>Plants:</b> Copies of copies";     
   if(name=="F2_nl") return "<b>Plants:</b> Ferns and other plants";     
   if(name=="F3_nl") return "<b>Plants:</b> Sunflower";     
   if(name=="F4_nl") return "<b>Plants:</b> Tree structures";     

   if(name=="G1_nl") return "<b>Games:</b> Sudoku";     
   if(name=="G2_nl") return "<b>Games:</b> 14/15 Puzzle";     
   if(name=="G3_nl") return "<b>Games:</b> Solitaire";     
   if(name=="G4_nl") return "<b>Games:</b> Free your car";     

   if(name=="H1_nl") return "<b>Simulations:</b> A walking robot";     
   if(name=="H2_nl") return "<b>Simulations:</b> Balancing seal";     
   if(name=="H3_nl") return "<b>Simulations:</b> Swarm simulation";     
   if(name=="H4_nl") return "<b>Simulations:</b> Inheritance playground";     
```

to the file at the appropriate location (you will see) and translate the titles from English to Dutch.

After committing, please let me know by commenting below. I think this pull request will also include the new commits then and I will see if everything is in place for merging into master.

**Comment by AndriesVansweevelt** [comment]
Thank you for the quick response. I forgot to copy the most recent functions.js file; I did now and I committed some minutes ago. If more is missing, please let me know!

**Comment by porst17** [comment]
Excuse my late reply. I am out office this week and will try look at your changes next week.

**Comment by AndriesVansweevelt** [comment]
There's no need to hurry, I'm out of office from september 1st until september 6th so I can't make any more changes until september 7th.

**Comment by porst17** [comment]
Due to #7, I had to `git-rebase` your changes onto the recent `master` branch and I also added the missing infrastructure (namely links for switching the language). Please apply further changes on top of https://github.com/IMAGINARY/cinderella-applets-2011-edition/master if necessary.

**Comment by porst17** [comment]
I published a new version at https://imaginary.org/applets/cinderella-applets-web/Cinderella-2011/index_nl.html

You can test the applets there provided that you have a Java plugin installed in your browser. The browser might ask you to confirm execution of the Java plugin since it is often considered unsafe.

Note that the applets might need some time to start upon first run. Be patient and resist from reloading the page for a couple of minutes (provided that you confirmed execution of the Java plugin).

**Pull request closed without merging**
